# One-time setup: make the HLTV Fantasy backend start automatically at logon and
# keep running (so nightly data ingestion happens with the app closed).
#
# No administrator rights required — it drops a hidden launcher in your per-user
# Startup folder. Run once:  .\scripts\install-autostart.ps1
# Remove with:               .\scripts\uninstall-autostart.ps1

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$root = Split-Path -Parent $scriptDir
. (Join-Path $scriptDir "backend-port.ps1")

# --- Ensure the venv + backend deps exist so autostart works from a clean box.
$venvPath = Join-Path $root ".venv"
$venvPy = Join-Path $venvPath "Scripts\python.exe"
if (-not (Test-Path $venvPy)) {
    Write-Host "Creating Python virtual environment..."
    python -m venv $venvPath
}
if (-not (Test-Path $venvPy)) {
    throw "venv Python not found at $venvPy (is Python installed and on PATH?)."
}
Write-Host "Installing backend dependencies..."
& $venvPy -m pip install --upgrade pip --quiet
& $venvPy -m pip install -r (Join-Path $root "requirements.txt") --quiet
if ($LASTEXITCODE -ne 0) { throw "pip install -r requirements.txt failed (exit $LASTEXITCODE)." }

# --- Drop a hidden VBS launcher in the Startup folder.
$runner = Join-Path $root "scripts\run-backend.ps1"
$startup = [Environment]::GetFolderPath("Startup")
$vbsPath = Join-Path $startup "HLTV-Fantasy-Backend.vbs"

# WScript.Shell.Run with window style 0 = fully hidden (no console flash).
$vbs = @"
' Auto-generated by install-autostart.ps1 -- launches the HLTV Fantasy backend
' hidden at logon and keeps it running. Delete this file (or run
' uninstall-autostart.ps1) to disable.
Set shell = CreateObject("WScript.Shell")
shell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$runner""", 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII
Write-Host "Installed autostart launcher: $vbsPath"

# --- Start it now so you don't have to log out/in.
Write-Host "Starting the backend now..."
Start-Process -FilePath "wscript.exe" -ArgumentList "`"$vbsPath`""

# The backend picks a free port and memorizes it in .runtime\backend-port.json;
# poll that file (up to ~20s) instead of assuming 8000.
$up = $false
for ($i = 0; $i -lt 40; $i++) {
    Start-Sleep -Milliseconds 500
    if (Test-BackendAlive) { $up = $true; break }
}
if ($up) {
    Write-Host "Backend is up ($(Get-BackendUrl)). It will now start automatically every time you log in." -ForegroundColor Green
} else {
    Write-Host "Backend not responding yet; it may still be starting. Logs: $env:LOCALAPPDATA\HLTVFantasy\logs (backend-latest.txt names the active one)." -ForegroundColor Yellow
}
